// Mocks generated by Mockito 5.4.6 from annotations
// in simple_pos/test/unit/core/services/backup_data_collector_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_pos/core/database/database_helper.dart' as _i13;
import 'package:simple_pos/features/inventory/data/datasources/daos/product_variant_dao.dart'
    as _i10;
import 'package:simple_pos/features/inventory/data/datasources/daos/variant_attribute_dao.dart'
    as _i11;
import 'package:simple_pos/services/database/dao/category_dao.dart' as _i5;
import 'package:simple_pos/services/database/dao/expense_dao.dart' as _i8;
import 'package:simple_pos/services/database/dao/payment_dao.dart' as _i4;
import 'package:simple_pos/services/database/dao/product_dao.dart' as _i2;
import 'package:simple_pos/services/database/dao/shift_dao.dart' as _i7;
import 'package:simple_pos/services/database/dao/supplier_dao.dart' as _i6;
import 'package:simple_pos/services/database/dao/transaction_dao.dart' as _i3;
import 'package:simple_pos/services/database/dao/user_dao.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDao_0 extends _i1.SmartFake implements _i2.ProductDao {
  _FakeProductDao_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionDao_1 extends _i1.SmartFake
    implements _i3.TransactionDao {
  _FakeTransactionDao_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentDao_2 extends _i1.SmartFake implements _i4.PaymentDao {
  _FakePaymentDao_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryDao_3 extends _i1.SmartFake implements _i5.CategoryDao {
  _FakeCategoryDao_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupplierDao_4 extends _i1.SmartFake implements _i6.SupplierDao {
  _FakeSupplierDao_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftDao_5 extends _i1.SmartFake implements _i7.ShiftDao {
  _FakeShiftDao_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpenseDao_6 extends _i1.SmartFake implements _i8.ExpenseDao {
  _FakeExpenseDao_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDao_7 extends _i1.SmartFake implements _i9.UserDao {
  _FakeUserDao_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductVariantDao_8 extends _i1.SmartFake
    implements _i10.ProductVariantDao {
  _FakeProductVariantDao_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVariantAttributeDao_9 extends _i1.SmartFake
    implements _i11.VariantAttributeDao {
  _FakeVariantAttributeDao_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_10 extends _i1.SmartFake implements _i12.Database {
  _FakeDatabase_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i13.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductDao get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _FakeProductDao_0(this, Invocation.getter(#products)),
          )
          as _i2.ProductDao);

  @override
  _i3.TransactionDao get transactions =>
      (super.noSuchMethod(
            Invocation.getter(#transactions),
            returnValue: _FakeTransactionDao_1(
              this,
              Invocation.getter(#transactions),
            ),
          )
          as _i3.TransactionDao);

  @override
  _i4.PaymentDao get payments =>
      (super.noSuchMethod(
            Invocation.getter(#payments),
            returnValue: _FakePaymentDao_2(this, Invocation.getter(#payments)),
          )
          as _i4.PaymentDao);

  @override
  _i5.CategoryDao get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _FakeCategoryDao_3(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i5.CategoryDao);

  @override
  _i6.SupplierDao get suppliers =>
      (super.noSuchMethod(
            Invocation.getter(#suppliers),
            returnValue: _FakeSupplierDao_4(
              this,
              Invocation.getter(#suppliers),
            ),
          )
          as _i6.SupplierDao);

  @override
  _i7.ShiftDao get shifts =>
      (super.noSuchMethod(
            Invocation.getter(#shifts),
            returnValue: _FakeShiftDao_5(this, Invocation.getter(#shifts)),
          )
          as _i7.ShiftDao);

  @override
  _i8.ExpenseDao get expenses =>
      (super.noSuchMethod(
            Invocation.getter(#expenses),
            returnValue: _FakeExpenseDao_6(this, Invocation.getter(#expenses)),
          )
          as _i8.ExpenseDao);

  @override
  _i9.UserDao get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUserDao_7(this, Invocation.getter(#users)),
          )
          as _i9.UserDao);

  @override
  _i10.ProductVariantDao get productVariants =>
      (super.noSuchMethod(
            Invocation.getter(#productVariants),
            returnValue: _FakeProductVariantDao_8(
              this,
              Invocation.getter(#productVariants),
            ),
          )
          as _i10.ProductVariantDao);

  @override
  _i11.VariantAttributeDao get variantAttributes =>
      (super.noSuchMethod(
            Invocation.getter(#variantAttributes),
            returnValue: _FakeVariantAttributeDao_9(
              this,
              Invocation.getter(#variantAttributes),
            ),
          )
          as _i11.VariantAttributeDao);

  @override
  _i14.Future<_i12.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i14.Future<_i12.Database>.value(
              _FakeDatabase_10(this, Invocation.getter(#database)),
            ),
          )
          as _i14.Future<_i12.Database>);

  @override
  _i14.Future<_i12.Database> initialize(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [filePath]),
            returnValue: _i14.Future<_i12.Database>.value(
              _FakeDatabase_10(
                this,
                Invocation.method(#initialize, [filePath]),
              ),
            ),
          )
          as _i14.Future<_i12.Database>);

  @override
  _i14.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);
}
