// Mocks generated by Mockito 5.4.6 from annotations
// in simple_pos/test/unit/features/pos/domain/usecases/checkout_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_pos/features/inventory/domain/entities/product.dart'
    as _i2;
import 'package:simple_pos/features/inventory/domain/repositories/product_repository.dart'
    as _i4;
import 'package:simple_pos/features/pos/domain/entities/cart_item.dart' as _i8;
import 'package:simple_pos/features/sales/domain/entities/payment_method.dart'
    as _i9;
import 'package:simple_pos/features/sales/domain/entities/transaction.dart'
    as _i5;
import 'package:simple_pos/features/sales/domain/repositories/transaction_repository.dart'
    as _i3;
import 'package:simple_pos/features/sales/domain/usecases/create_transaction_usecase.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionRepository_1 extends _i1.SmartFake
    implements _i3.TransactionRepository {
  _FakeTransactionRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductRepository_2 extends _i1.SmartFake
    implements _i4.ProductRepository {
  _FakeProductRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_3 extends _i1.SmartFake implements _i5.Transaction {
  _FakeTransaction_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Product>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i6.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i6.Future<List<_i2.Product>>);

  @override
  _i6.Future<_i2.Product> getProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i6.Future<_i2.Product>.value(
              _FakeProduct_0(this, Invocation.method(#getProductById, [id])),
            ),
          )
          as _i6.Future<_i2.Product>);

  @override
  _i6.Future<_i2.Product> addProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i6.Future<_i2.Product>.value(
              _FakeProduct_0(this, Invocation.method(#addProduct, [product])),
            ),
          )
          as _i6.Future<_i2.Product>);

  @override
  _i6.Future<void> updateProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getStock(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getStock, [productId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> updateStock(int? productId, int? newStock) =>
      (super.noSuchMethod(
            Invocation.method(#updateStock, [productId, newStock]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Product>> searchProducts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [query]),
            returnValue: _i6.Future<List<_i2.Product>>.value(<_i2.Product>[]),
          )
          as _i6.Future<List<_i2.Product>>);

  @override
  _i6.Future<bool> productExists(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#productExists, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [CreateTransactionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTransactionUseCase extends _i1.Mock
    implements _i7.CreateTransactionUseCase {
  MockCreateTransactionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TransactionRepository get transactionRepository =>
      (super.noSuchMethod(
            Invocation.getter(#transactionRepository),
            returnValue: _FakeTransactionRepository_1(
              this,
              Invocation.getter(#transactionRepository),
            ),
          )
          as _i3.TransactionRepository);

  @override
  _i4.ProductRepository get productRepository =>
      (super.noSuchMethod(
            Invocation.getter(#productRepository),
            returnValue: _FakeProductRepository_2(
              this,
              Invocation.getter(#productRepository),
            ),
          )
          as _i4.ProductRepository);

  @override
  _i6.Future<_i5.Transaction> execute({
    required List<_i8.CartItem>? cart,
    required _i9.PaymentMethod? paymentMethod,
    double? cashReceived,
    String? cardLast4Digits,
    String? notes,
    double? tax = 0.0,
    double? discount = 0.0,
    int? cashierId,
    String? cashierName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #cart: cart,
              #paymentMethod: paymentMethod,
              #cashReceived: cashReceived,
              #cardLast4Digits: cardLast4Digits,
              #notes: notes,
              #tax: tax,
              #discount: discount,
              #cashierId: cashierId,
              #cashierName: cashierName,
            }),
            returnValue: _i6.Future<_i5.Transaction>.value(
              _FakeTransaction_3(
                this,
                Invocation.method(#execute, [], {
                  #cart: cart,
                  #paymentMethod: paymentMethod,
                  #cashReceived: cashReceived,
                  #cardLast4Digits: cardLast4Digits,
                  #notes: notes,
                  #tax: tax,
                  #discount: discount,
                  #cashierId: cashierId,
                  #cashierName: cashierName,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.Transaction>);
}
